### ISSUE TITLE
نتيجه البحث غير صحيحه ابدا

### ISSUE THREAD

**Issue by futurevoid** [AhmedElTabarani/dorar-hadith-api#3]
هذا ال url 
``https://dorar-hadith-api.cyclic.app/api/search?value=انما الاعمال بالنيات&page=2``

نتيجيته 

hadith | "{وَمَا أَفَاءَ اللَّهُ عَلَى رَسُولِهِ مِنْهُمْ فَمَا أَوْجَفْتُمْ عَلَيْهِ مِنْ خَيْلٍ وَلَا رِكَابٍ} [الحشر: 6]، قال الزُّهريُّ: قال عُمَرُ: هذه لرسولِ اللهِ صلَّى اللهُ عليه وسلَّمَ خاصَّةً قُرَى [عُرَيْنةَ] فَدَكُ، وكذا وكذا مِن {مَا أَفَاءَ اللَّهُ عَلَى رَسُولِهِ مِنْ أَهْلِ الْقُرَى فَلِلَّهِ وَلِلرَّسُولِ وَلِذِي الْقُرْبَى وَالْيَتَامَى وَالْمَسَاكِينِ وَابْنِ السَّبِيلِ} [الحشر: 7]، و{لِلْفُقَرَاءِ الْمُهَاجِرِينَ الَّذِينَ أُخْرِجُوا مِنْ دِيَارِهِمْ وَأَمْوَالِهِمْ} [الحشر: 8]، {وَالَّذِينَ تَبَوَّؤُوا الدَّارَ وَالْإِيمَانَ مِنْ قَبْلِهِمْ} [الحشر: 9]، {وَالَّذِينَ جَاؤُوا مِنْ بَعْدِهِمْ} [الحشر: 10]، فاستَوعَبتْ هذه الآيةُ الناسَ، فلم يَبقَ أحدٌ مِن المسلمينَ إلَّا له فيها حقٌّ -قال أيُّوبُ: أو قال: حظٌّ- إلَّا بعضَ مَن تَملِكونَ مِن أَرِقَّائِكم.  ."
-- | --
el_rawi | "عمر"
el_mohdith | "شعيب الأرناؤوط"
source | "تخريج سنن أبي داود"
number_or_page | "2966"
grade | "رجاله ثقات، إلا أنه منقطع\n، لكن قول عمر في آخره: لم يبق أحد من المسلمين إلا له فيها حق إلا بعض من تملكون من أرقائكم، صحيح"
1 |  
hadith | "سُئِلَ النبيُّ صَلَّى اللهُ عليه وسلَّمَ عَنِ الحُمُرِ، فَقالَ: لَمْ يُنْزَلْ عَلَيَّ فِيهَا شيءٌ إلَّا هذِه الآيَةُ الجَامِعَةُ الفَاذَّةُ: {فمَن يَعْمَلْ مِثْقالَ ذَرَّةٍ خَيْرًا يَرَهُ، ومَن يَعْمَلْ مِثْقالَ ذَرَّةٍ شَرًّا يَرَهُ} [الزلزلة: 7، 8].  ."
el_rawi | "أبو هريرة"
el_mohdith | "البخاري"
source | "صحيح البخاري"
number_or_page | "4963"
grade | "[صحيح]"
2 |  
hadith | "سُئِل رسولُ اللهِ صلَّى اللهُ عليه وسلَّم عنِ الحُمُرِ فقال لَمْ يَأْتِ فيها شيءٌ إلَّا هذه الآيةُ الفاذَّةُ الجامعةُ: {فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ * وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ} [الزلزلة: 7، 8]  ."
el_rawi | "أبو هريرة"
el_mohdith | "الطبراني"
source | "المعجم الأوسط"
number_or_page | "6/231"
grade | "لم يرو هذا الحديث عن سفيان إلا سعيد بن منصور"
3 |  
hadith | "سُئِلَ رسولُ اللهِ صلَّى اللهُ عليه وسلَّمَ عنِ الحَميرِ: فيها زَكاةٌ؟ فقال: ما جاءَني فيها شيءٌ إلَّا هذه الآيةُ الفاذَّةُ: {مَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ * وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ} [الزلزلة: 7 - 8]  ."
el_rawi | "أبو هريرة"
el_mohdith | "شعيب الأرناؤوط"
source | "تخريج المسند لشعيب"
number_or_page | "9476"
grade | "إسناده صحيح على شرط مسلم"
4 |  
hadith | "عنْ صَعْصَعةَ بنِ مُعَاويةَ، قدِمْتُ على النَّبيِّ صلَّى اللهُ عليه وسلَّمَ فسمِعْتُه يقولُ هذه الآيةَ: {فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ (7) وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ} [الزلزلة: 8]، فقُلْتُ: لا أُبالي ألَّا أسمَعَ غيرَها حَسْبي حَسْبي.  ."
el_rawi | "الحسن"
el_mohdith | "الحاكم"
source | "المستدرك على الصحيحين"
number_or_page | "6736"
grade | "[سكت عنه وقال في المقدمة رواته ثقات احتج بمثله الشيخان أو أحدهما]"
5 |  
hadith | "بيْنَا أبو بكرٍ الصِّدِّيقُ رَضيَ اللهُ عنه يَتغدَّى مع رسولِ اللهِ صلَّى اللهُ عليه وسلَّمَ إذ نَزَلَتْ هذه الآيةُ: {فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ (7) وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ} [الزلزلة: 7، 8] فأَمسَكَ أبو بكرٍ وقالَ: يا رسولَ اللهِ، أكُلُّ ما عَمِلنا مِن سوءٍ رَأيناهُ؟ فقالَ: «ما تَروْنَ ممَّا تَكرهونَ فذلك ما تُجزَوْنَ، يُؤخَّرُ الخيرُ لأهلِهِ في الآخرةِ».   ."
el_rawi | "أبو أسماء الرحبي"
el_mohdith | "الحاكم"
source | "المستدرك على الصحيحين"
number_or_page | "4014"
grade | "صحيح الإسناد"
6 |  
hadith | "قال ابنُ عبَّاسٍ: ثَمانِ آياتٍ في سُورةِ النِّساءِ هي خَيرٌ لهذه الأُمَّةِ ممَّا طلَعَت عليه الشَّمسُ، أوَّلُهنَّ:\n1- {يُرِيدُاللَّهُلِيُبَيِّنَلَكُمْ} [النساء: 26].\n2 - {وَاللَّهُيُرِيدُأَنْيَتُوبَعَلَيْكُمْ} [النساء: 27].\n3 - {وَاللَّهُيُرِيدُأَنْيَتُوبَعَلَيْكُمْ} [النساء: 27].\n4 - {إِنْتَجْتَنِبُواكَبَائِرَمَاتُنْهَوْنَعَنْهُ} [النساء: 31].\n5 - {إِنَّاللَّهَلَايَغْفِرُأَنْيُشْرَكَبِهِ} [النساء: 48].\n6 - {إِنَّاللَّهَلَايَظْلِمُمِثْقَالَذَرَّةٍ} [النساء: 40].\n7 - {وَمَنْيَعْمَلْسُوءًاأَوْيَظْلِمْنَفْسَهُ} [النساء: 110].\n8 - {مَايَفْعَلُاللَّهُبِعَذَابِكُمْ} [النساء: 147].  ."
el_rawi | "قتادة"
el_mohdith | "زين الدين المناوي"
source | "الفتح السماوي"
number_or_page | "359"
grade | "[فيه] صالح ضعيف، وقتادة عنِ ابنِ عبَّاسٍ منقطع"
7 |  
hadith | "بيْنما أبو بَكرٍ رضيَ اللهُ عنه قاعِدٌ مع رسولِ اللهِ صلَّى اللهُ عليه وسلَّمَ، إذْ نزَلَتْ هذِه الآيةُ: {فَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ خَيْرًا يَرَهُ * وَمَنْ يَعْمَلْ مِثْقَالَ ذَرَّةٍ شَرًّا يَرَهُ } [الزلزلة: 7، 8]، قال: فأَمسَكَ أبو بَكرٍ، وقال: يا رسولَ اللهِ، ما عَمِلْنا مِن سوءٍ أُتِيناهُ؟ فقال: «ما تَرَوْنَ ممَّا تَكرَهونَ فذاكَ ما تُجْزَوْنَ بهِ، ويؤَخَّرُ الخَيرُ لأهْلِه في الآخِرةِ».  ."
el_rawi | "أبو بكر الصديق"
el_mohdith | "شعيب الأرناؤوط"
source | "تخريج مسند أبي بكر"
number_or_page | "113"
grade | "رجاله ثقات لكنه مرسل"
8 |  
hadith | "أنَّ اليهودَ كانوا يقولونَ لِرسولِ اللهِ صلَّى اللهُ عليه وسلَّمَ: سامٌ عليك! ثُمَّ يقولونَ في أنفُسِهم: {لَوْلَا يُعَذِّبُنَا اللهُ بِمَا نَقُولُ} [المجادلة:8]، فنزَلَتْ هذه الآيةُ {وَإِذَا جَاؤُوكَ حَيَّوْكَ بِمَا لَمْ يُحَيِّكَ بِهِ اللهُ} [المجادلة:8] إلى آخِرِ الآيةِ.  ."
el_rawi | "عبدالله بن عمرو"
el_mohdith | "شعيب الأرناؤوط"
source | "تخريج المسند لشعيب"
number_or_page | "6589"
grade | "صحيح"
9 |  
hadith | "أنَّ اليهودَ أتَتِ النَّبيَّ صلَّى اللهُ عليه وسلَّمَ فقالتْ: السَّامُ عليكَ، وقالوا في أنفُسِهم: {لَوْلَا يُعَذِّبُنَا اللَّهُ بِمَا نَقُولُ} [المجادلة: 8]، فأنزَلَ اللهُ عزَّ وجلَّ: {وَإِذَا جَاؤُوكَ حَيَّوْكَ بِمَا لَمْ يُحَيِّكَ بِهِ اللَّهُ} -فقرَأَ إلى قَولِه- {فَبِئْسَ الْمَصِيرُ} [المجادلة: 8].  ."
el_rawi | "عبدالله بن عمرو"
el_mohdith | "شعيب الأرناؤوط"
source | "تخريج المسند لشعيب"
number_or_page | "7061"
grade | "صحيح لغيره"

ارجو المساعده و جزاكم الله خيرا

**Comment by AhmedElTabarani** [comment]
أين المشكلة بالتحديد؟

**Comment by AhmedElTabarani** [comment]
لقد فهمت المشكلة، وتم حلها حاول مجددًا

**Comment by futurevoid** [comment]
جزاك الله خيرا , المشكله اتحلت
