### ISSUE TITLE
الموقع لا يعمل

### ISSUE THREAD

**Issue by futurevoid** [AhmedElTabarani/dorar-hadith-api#5]
هذا ما يظهر لي 

{"status":"error","message":"There is no router for this url, Please check docs '/docs'"}

**Comment by AhmedElTabarani** [comment]
أنا عملت تعديلات على الـ endpoint  ممكن تتفقدها في /docs أو تقرأ الـ README

أنا بعتذر لو التغير دة اثر على مشروعك
لكن الان الـ API وصل لمرحلة الاستقرار مع V1

**Comment by AhmedElTabarani** [comment]
لقد قمت بعمل PR لمشروعك لإصلاح المشكلة https://github.com/futurevoid/HadithSearch/pull/1
وأيضًا قمت بشرح التغيرات لك هناك

**Comment by AhmedElTabarani** [comment]
@futurevoid 
لو المشكلة اتحلت ممكن تقفل الـ issue

**Comment by futurevoid** [comment]
جزاك الله خير الجزاء ❤️
