### ISSUE TITLE
هل هنالك إي بي آي لإيجاد حديث معين ؟

### ISSUE THREAD

**Issue by abdulhakim-alshanqiti** [AhmedElTabarani/dorar-hadith-api#7]
انا لدي روابط للأحاديث على موقع الدرر كيف يمكنني ان أحول الأحاديث إلى صيغة json عند بناء موقعي؟

**Comment by AhmedElTabarani** [comment]
معاك روابط لاحاديث مثل هذا https://dorar.net/h/45wXAdej
وتريد استخدام الـ id الخاص به `45wXAdej` لتحويله لـ json

~~ممكن تستعمل `/v1/site/hadith/similar/:id` سيحضر لك الاحاديث المشابه واول حديث هو صاحب الـ id
أو ممكن تنتظر لاخر الاسبوع وسأقوم بعمل api جديد يحضر لك الحديث بناءا عن الـ id~~


لقد قمت باضافة endpoint جديد، ممكن تستعمل `/v1/site/hadith/:id` سيحضر لك الحديث صاحب الـ id
PR: #8
